#!/usr/bin/env bash
# A script that transfers a file from our client to a server:
# USAGE: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ $# -lt 3 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path=$1
ip=$2
usrname=$3
ssh_key=$4

scp -i "$ssh_key" -o StrictHostKeyChecking=no "$path" "$usrname@$ip:~/"
