#!/usr/bin/env bash
#update package list and install Nginx
sudo apt-get update -y
sudo apt-get -y install nginx

echo "Hello, World!" | sudo tee /var/www/html/index.html

#backup the default nginx site configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

#configure Ngnix to serve the custom HTML page
sudo bash -c 'cat > /etc/nginx/sites-avaliable/default' << EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	server_name_;

	location / {
		try_files \$uri \$uri/ =404;
	}
}
EOF

#Reload Nginx to apply the changes without systemctl
sudo service nginx restart

#Test Nginx configuration
sudo nginx -t
