#!/usr/bin/env bash
#update package list and install Nginx
sudo apt update
sudo apt install -y nginx

echo "Hello, World!" | sudo tee /var/www/html/index.html

#Reload Nginx to apply the changes without systemctl
sudo service nginx reload

#Test Nginx configuration
sudo nginx -t
