#!/usr/bin/env bash
# A script that generates a MySQL dump and creates a compressed archive out of it.

MYSQL_ROOT_PASSWORD=$1

BACKUP_FILE="backup.sql"

DATE=$(date +%d-%m-%y)

sudo mysqldump -u root -p"${MYSQL_ROOT_PASSWORD}" --all-databases | sudo tee "${BACKUP_FILE}" > /dev/null

tar -czvf "${DATE}.tar.gz" ${BACKUP_FILE}
