#!/usr/bin/env bash
#Displays "Best School" 10 times but changes 9th iteration to Hi
(( endPoint=10 ))
(( startPoint=1 ))

while [ $startPoint -le $endPoint ]
do
	echo "Best School"
	if [ $startPoint -eq 9 ]
	then
		echo "Hi"
	fi
	((startPoint+=1))
done
