#!/usr/bin/env bash
# Get Apache to run on container and return a page
# containing Hello Holberton when root is querred

docker run -p 8080:80 -d -it holbertonschool/265-0

docker ps

docker exec -it <container_id> /bin/bash

apt-get update
apt-get install -y apache2

echo "Hello Holberton" > /var/www/html/index.html

service apache2 start
